# Generated by Django 3.2.3 on 2024-09-05 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('reference', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
                ('quantite_entree', models.IntegerField(null=True)),
                ('quantite_sortie', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('responsable', models.CharField(choices=[('Abas', 'Abas'), ('Zakir', 'Zakir'), ('Roger', 'Roger'), ('Azmat', 'Azmat')], default='Abas', max_length=100)),
                ('centre', models.CharField(choices=[('Antaniavo', 'Antaniavo'), ('Andakana', 'Andakana'), ('Manakara', 'Manakara')], default='Antaniavo', max_length=100)),
                ('date_entree', models.DateField(blank=True, null=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('action', models.CharField(choices=[('entree', 'entree'), ('sortie', 'sortie')], max_length=100)),
                ('qantite', models.IntegerField(null=True)),
                ('reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.depot')),
            ],
        ),
    ]
