# Generated by Django 3.2.3 on 2024-09-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquedepot',
            name='qantite',
            field=models.IntegerField(default=0),
        ),
    ]
