# Generated by Django 3.2.3 on 2024-09-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_historiquedepot_qantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='type',
            field=models.CharField(choices=[('Electique', 'Electique'), ('Plomberie', 'Plomberie')], default='Electique', max_length=100),
        ),
    ]
