# Generated by Django 3.2.3 on 2024-09-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_depot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='depot',
            name='quantite_entree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depot',
            name='quantite_sortie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
