# Generated by Django 3.2.3 on 2024-09-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20240905_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
