# Generated by Django 3.2.3 on 2024-09-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_depot_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='quantite_entree',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='depot',
            name='quantite_sortie',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
