# Generated by Django 3.2.3 on 2024-09-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20240905_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='type',
            field=models.CharField(choices=[('Electique', 'Electique'), ('Plomberie', 'Plomberie'), ('Construction', 'Construction'), ('Jeux', 'Jeux'), ('Vetement', 'Vetement'), ('Accessoir', 'Accessoir')], default='Electique', max_length=100),
        ),
    ]
