# Generated by Django 3.2.25 on 2024-09-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_depot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquedepot',
            name='motif',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historiquedepot',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
