# Generated by Django 3.2.3 on 2024-10-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_depotlivre_historiquedepotlivre'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='responsable',
            field=models.CharField(choices=[('Abas', 'Abas'), ('Zakir', 'Zakir'), ('Roger', 'Roger'), ('Azmat', 'Azmat'), ('Sheck Salman', 'Sheck Salman')], default='Abas', max_length=100),
        ),
    ]
