# Generated by Django 3.2.3 on 2024-10-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20241007_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='quantite_entree',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='depot',
            name='quantite_sortie',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
