# Generated by Django 3.2.3 on 2024-10-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20241011_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquedepot',
            name='qantite',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
