# Generated by Django 3.2.3 on 2024-10-23 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_historiquedepot_qantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquedepotlivre',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.depotlivre'),
        ),
    ]
