# Generated by Django 3.2.3 on 2025-01-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_historiquedepotlivre_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquedepot',
            name='action',
            field=models.CharField(choices=[('entree', 'entree'), ('sortie', 'sortie'), ('retour', 'retour')], max_length=100),
        ),
    ]
